# ------------------------------------------------------- #
# Note: this file originates in template-action-composite #
# ------------------------------------------------------- #

version: '3.8'

services:
  # ---- super-linter ---- #
  lint:
    image: ghcr.io/super-linter/super-linter:slim-v8.5.0
    volumes:
      - ./:/github/workspace
    environment:
      RUN_LOCAL: 'true'
      LOG_LEVEL: 'ERROR'
      MULTI_STATUS: 'false'
      VALIDATE_JSCPD: 'false'
      IGNORE_GITIGNORED_FILES: 'true'
      DEFAULT_WORKSPACE: /github/workspace
      FILTER_REGEX_EXCLUDE: '/github/workspace/README.md'

  # ---- readme generator ---- #
  readme:
    image: pandoc/core:3.6
    volumes:
      - ./:/data
    command: --defaults=.pandoc.yml
